message: Fix error while running with python3
Error:
----------
Traceback (most recent call last):
  File "widget_demo.py", line 29, in <module>
    from message import display_message
  File "/media/vijai/data/workspace/GooeyExamples/examples/message.py", line 32
    print line
             ^
SyntaxError: Missing parentheses in call to 'print'
----------

Signed-off-by: Vijai Kumar K <vijaikumar.kanagarajan@gmail.com>